// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nutnjfmhnkicxlwtuuwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dG5qZm1obmtpY3hsd3R1dXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDM0OTIsImV4cCI6MjA2MzIxOTQ5Mn0.dwABU2pViVhvFc0HZlrzIBbH5PducyqnhZwLAWjThrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);